name:                math-parse
version:             0.2.0.0
github:              "dylan-thinnes/math-parse"
license:             MIT
author:              "Dylan Thinnes"
maintainer:          "dylan.thinnes@protonmail.com"
copyright:           "2019 Dylan Thinnes"
synopsis:            "Parses & calculate integral mathematical expressions."
description:         |
  math-parse parses integral mathematical expressions into ASTs and provides
  machinery to reduce ASTs into a final calculation with safeguards against
  large calculations.
category:            "math"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dylan-thinnes/math-parse#readme>

dependencies:
- base >= 4.7 && < 5
- recursion-schemes >= 5.1 && < 6
- text
- parser-combinators

library:
  source-dirs: src
