name:                math-parse
version:             0.2.0.0
github:              "dylan-thinnes/math-parse"
license:             MIT
author:              "Dylan Thinnes"
maintainer:          "dylan.thinnes@protonmail.com"
copyright:           "2019 Dylan Thinnes"
synopsis:            "Parses & calculate integral mathematical expressions."
description:         |
  math-parse parses integral mathematical expressions into ASTs and provides
  machinery to reduce ASTs into a final calculation with safeguards against
  large calculations.

  Please see the README on GitHub at <https://github.com/dylan-thinnes/math-parse#readme>
category:            "Math"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- recursion-schemes >= 5.1 && < 6
- text
- parser-combinators

library:
  source-dirs: src
